module gobits_gen;

import std.stdio;
import std.file;

void main()
{
	auto f = File("gobits/tables.d", "w");
	scope(exit) f.close();

	f.writeln("module gobits.tables;\n");
	f.writeln("import std.stdint : uint8_t;\n");
	f.writeln("// Code generated by `rdmd make-tables.d`. WARNING :: DO NOT EDIT!!!\n");

	gen(f, "ntz8tab", &ntz8);
	gen(f, "pop8tab", &pop8);
	gen(f, "rev8tab", &rev8);
	gen(f, "len8tab", &len8);

}

void gen(scope File f, string name, ubyte function(ubyte) cb) {

	f.write("immutable uint8_t[256] " ~ name ~ " = [");

	for(int i = 0; i < 256; i++) {
		if (i%16 == 0) {
			f.write("\n\t");
		} else {
			f.write(" ");
		}

		f.writef("0x%.2x%s", cb(cast(ubyte)i), i < 255 ? "," : "\n");
	}

	f.writeln("];\n\n");

}

ubyte ntz8(ubyte x) {
	ubyte n = 0;

	while( (x&1) == 0 && n < 8 ) {
		x >>= 1;
		n++;
	} 

	return n;
}

ubyte pop8(ubyte x) {
	ubyte n = 0;

	while(x != 0) {
		x &= x - 1;
		n++;
	}

	return n;
}

ubyte rev8(ubyte x) {
	ubyte r = 0;

	for(ubyte i = 8; i > 0; i --) {
		r = cast(ubyte)( (r<<1) | (x&1) );
		x >>= 1;
	}

	return r;
}


ubyte len8(ubyte x) {
	ubyte n = 0;

	while(x != 0) {
		x >>= 1;
		n++;
	}

	return n;
}